name: CI on Linux

on:
  push:
    branches:
      # Push events to branches matching refs/heads/master
      - 'master'
      - 'devel'
  pull_request:

env:
  TZ: Atlantic/Reykjavik

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "gcc-10"
            cxx: "g++-10"
            cc: "gcc-10"
            pkg: "g++-10 gcc-10" 
            cxx_flags: "-std=c++20"
            build_type: Debug

          - name: "gcc-11"
            cxx: "g++-11"
            cc: "gcc-11"
            pkg: "g++-11 gcc-11"
            cxx_flags: "-std=c++20"
            build_type: Release

          - name: "clang-10"
            cxx: "clang++-10"
            cc: "clang-10"
            pkg: "clang-10 libomp5-10 libomp-10-dev"
            cxx_flags: "-std=c++20"
            build_type: Debug

          - name: "clang-13"
            cxx: "clang++-13"
            cc: "clang-13"
            pkg: "clang-13 libomp5-13 libomp-13-dev"
            cxx_flags: "-std=c++20"
            build_type: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src
          fetch-depth: 2
          submodules: recursive

      - name: Add package source
        run: |
          echo 'APT::Acquire::Retries "5";' | sudo tee -a /etc/apt/apt.conf.d/80-retries > /dev/null
          sudo add-apt-repository --no-update --yes ppa:ubuntu-toolchain-r/ppa
          sudo add-apt-repository --no-update --yes ppa:ubuntu-toolchain-r/test
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository --no-update --yes "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main"
          sudo add-apt-repository --no-update --yes "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
          sudo apt-get update

      - name: Install CMake
        run: sudo apt-get install --yes cmake

      - name: Install ccache
        run: sudo apt-get install --yes ccache

      - name: Install compiler ${{ matrix.name }}
        run: sudo apt-get install --yes ${{ matrix.pkg }}

      - name: Load ccache
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../src -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}"

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 6
          CCACHE_MAXSIZE: 500M
        run: |
          ccache -p || true
          cd build
          make -k -j2
          ccache -s || true

      - name: Run tests
        run: |
          cd build
          make test
